#!/bin/sh
# This script runs inside the hashicorp/terraform container
# It listens for new Terraform files generated by the Infra service and applies them.

# Utility to parse JSON using grep/sed since jq might not be in the terraform alpine image
get_json_val() {
    grep -o "\"$1\": *\"[^\"]*\"" /app/data/credentials.json | grep -o '"[^"]*"$' | sed 's/"//g'
}

echo "Deployment Worker Started..."
echo "Waiting for Terraform configurations in /app/templates..."

while true; do
    for dir in /app/templates/*/; do
        if [ -d "$dir" ] && [ -f "$dir/main.tf" ] && [ ! -f "$dir/.applied" ]; then
            echo "New deployment detected in $dir"
            
            # Load credentials if they exist
            if [ -f "/app/data/credentials.json" ]; then
                echo "Loading dynamic Azure credentials..."
                export ARM_CLIENT_ID=$(get_json_val "clientId")
                export ARM_CLIENT_SECRET=$(get_json_val "clientSecret")
                export ARM_TENANT_ID=$(get_json_val "tenantId")
                export ARM_SUBSCRIPTION_ID=$(get_json_val "subscriptionId")
            else
                echo "Warning: No credentials.json found. Relying on environment variables."
            fi

            cd "$dir"
            
            echo "Initializing Terraform..."
            terraform init -no-color > init.log 2>&1
            
            echo "Planning Deployment..."
            terraform plan -out=tfplan -no-color > plan.log 2>&1
            
            # In a real environment, this stops here and waits for user approval via the DB
            echo "Applying Deployment (Auto-Approve for MVP)..."
            terraform apply -auto-approve tfplan -no-color > apply.log 2>&1
            
            touch .applied
            echo "Deployment completed for $dir"
        fi
    done
    sleep 5
done
